spring:
  datasource:
    url: jdbc:mysql://localhost:3306/billpayment
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  jwt:
    secret: "FDA6A5B0436E06FB69F8A89FA6E2E89798E164935BFB4AD099748C2480E4AE2A"

mail:
  host: smtp.gmail.com
  port: 25
  username: eben4nkusi@gmail.com
  password: cckuwntpxlojwxxx

  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true

server:
  port: 8084